config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :users
      resources :skill_tags
      resources :user_skill_tags
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill_tag.rb
class SkillTag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :user_skill_tags, dependent: :destroy
  has_many :users, through: :user_skill_tags

  def get_detail_added_to(user_id)
    user = User.find(user_id)
    
    user_skill_tags = user.user_skill_tags.where(skill_tag_id: self.id)
    added_skill_tag = {
      id: self.id,
      name: self.name,
      user_skill_tags: user_skill_tags,
      count: user_skill_tags.count,
      added_by: User.where(id: user_skill_tags.pluck(:added_by))
    }

    return added_skill_tag
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates(:name, presence: true)
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :user_skill_tags, foreign_key: 'user_id', dependent: :destroy
#  has_many :user_skill_tags, foreign_key: 'added_by', dependent: :destroy
  has_many :skill_tags, through: :user_skill_tags
  has_secure_password
end

app/models/user_skill_tag.rb
class UserSkillTag < ApplicationRecord
  belongs_to :user
  belongs_to :skill_tag

  validates :user_id, uniqueness: { scope: [:skill_tag_id, :added_by] }
end

app/controllers/api/v1/application_controller.rb
module Api
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :expception
    skip_before_filter :verify_authenticity_token
  end
end

app/controllers/api/v1/skill_tags_controller.rb
module Api
  module V1
    class SkillTagsController < ApplicationController
      def create
        user_id = skill_tag_params[:user_id]
        added_by = skill_tag_params[:added_by]
        skill_tag_name = skill_tag_params[:skill_tag]

        skill_tag = SkillTag.find_by(name: skill_tag_name)

        if skill_tag.nil?
          skill_tag = SkillTag.new(name: skill_tag_name)
          if skill_tag.save
            user_skill_tag = UserSkillTag.new(
              user_id: user_id,
              added_by: added_by,
              skill_tag_id: skill_tag.id
            )
            if user_skill_tag.save
              @added_skill_tag = skill_tag.get_detail_added_to(user_id)
            else
              skill_tag.destroy()
            end
          end
        else   
          user_skill_tag = UserSkillTag.new(skill_tag_id: skill_tag.id, user_id: user_id, added_by: added_by)
          if user_skill_tag.save
            @added_skill_tag = skill_tag.get_detail_added_to(user_id)
          end
        end

        render json: @added_skill_tag
      end

      private

      def skill_tag_params
        params.permit(:skill_tag, :user_id, :added_by, :format)
      end
    end
  end
end

app/controllers/api/v1/user_skill_tags_controller.rb
module Api
  module V1
    class UserSkillTagsController < ApplicationController
      def create 
        params = user_skill_tag_params
        params.delete(:format)
        user_skill_tag = UserSkillTag.new(params)

        if user_skill_tag.save
          skill_tag = SkillTag.find(user_skill_tag_params[:skill_tag_id])
          @added_skill_tag = skill_tag.get_detail_added_to(user_skill_tag_params[:user_id])
        end

        render json: @added_skill_tag
      end

      private
       
      def user_skill_tag_params
        params.permit(:skill_tag_id, :user_id, :added_by, :format)
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def show
        user = User.find(params[:id])
        added_skill_tags = user.skill_tags.uniq{|skill| skill.name}.map do |skill_tag|
          user_skill_tags = user.user_skill_tags.where(skill_tag_id: skill_tag.id)
          {
            id: skill_tag.id,
            name: skill_tag.name,
            user_skill_tags: user_skill_tags,
            count: user_skill_tags.count,
            added_by: skill_tag.users,
          }
        end
        @user = {
          id: user.id,
          name: user.name,
          added_skill_tags: added_skill_tags,
        }
        render json: @user
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :check_user_session
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_user_session

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show 
    @user = User.find(params[:id])
  end 

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def check_user_session
    unless logged_in?
      redirect_to login_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IzumealSkillApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class='navbar navbar-fixed-top navbar-inverse'>
      <div class='container'>
        <%= link_to 'SkillTagManager', users_path, id: 'logo' %>
        <nav>
          <ul class='nav navbar-nav navbar-right'>
            <% if logged_in? %>
              <li><%= link_to 'Users List', users_path %></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Log in', login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <% flash.each do |message_type, message| %>
      <div class='alert alert-<%= message_type %>'><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(@user.errors.count, 'error') %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>users list</h1>

<div class='users_list'>
  <% @users.each do |user| %>
    <ul>
      <li><%= user.name %> <%= link_to 'detail', user_path(user) %></li>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= render 'shared/users/error_messages' %>

    <%= form_for(@user, url: signup_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit 'Create my account', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Profile</h1>

<h2>Name: <%= @user.name %></h2>
<%= react_component('SkillTagBox', current_user: current_user) %>
<script>
  ReactRailsUJS.mountComponents()
</script>